version: 2.1
jobs:
  lint:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: npm i
      - run: npm run test
workflows:
  version: 2
  test:
    jobs:
      - lint
      - test:
          requires:
            - lint